version: "3.9"
services:
  api:
    container_name: fastapi-beer
    restart: always
    build: 
      context: "api"
      dockerfile: "Dockerfile"
    ports:
      - "8000:80"
  frontend:
    container_name: frontend-beer
    restart: always
    build: 
      context: "frontend"
      dockerfile: "docker/Dockerfile"
    depends_on:
      - api
    ports:
      - "8080:80"